### ISSUE TITLE
Add exclude options?

### ISSUE THREAD

**Issue by Smilefish2** [iguntur/laravel-blade-jade#1]
First , thank you very much for your work,cool.
Then, Can add pug extension Support and Add exclude options?

**Comment by iguntur** [comment]
@Smilefish2, currently `pug` extension is not supported for this project, I think is possible on another project meaning by convention naming.

can you explain me about `exclude` options?

if you mean to exclude and sure not to compile or render them, you can prefix the filename with `_` instead.
eg: `_sidebar.jade`.
